name: flutter_setup
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.5
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  intl: ^0.18.0
  logger: ^1.1.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
